### ISSUE TITLE
haproxy-ingress canary dumps core when trying to use ssl-passthrough

### ISSUE THREAD

**Issue by jvanbruegge** [jcmoraisjr/haproxy-ingress#259]
When creating an ingress with the `ssl-passthrough` annotation, the haproxy pod crashes with this log output:
```
I1130 22:45:59.362355       5 launch.go:142] 
Name:       HAProxy
Release:    v0.7-beta.2
Build:      git-8875595
Repository: https://github.com/jcmoraisjr/haproxy-ingress
I1130 22:45:59.362404       5 launch.go:145] Watching for ingress class: haproxy
I1130 22:45:59.362562       5 launch.go:345] Creating API client for https://10.96.0.1:443
I1130 22:45:59.367565       5 launch.go:357] Running in Kubernetes Cluster version v1.10 (v1.10.0) - git (clean) commit fc32d2f3698e36b93322a3465f63a14e9f0eaead - platform linux/amd64
I1130 22:45:59.368931       5 launch.go:169] validated default/ingress-default-backend as the default backend
I1130 22:45:59.373212       5 controller.go:1483] starting Ingress controller
I1130 22:45:59.380613       5 event.go:218] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"default", Name:"vault", UID:"5d353da1-f4f1-11e8-b72e-0800277849aa", APIVersion:"extensions", ResourceVersion:"139744", FieldPath:""}): type: 'Normal' reason: 'CREATE' Ingress default/vault
I1130 22:46:04.674928       5 controller.go:1491] running initial sync of secrets
W1130 22:46:04.677344       5 controller.go:893] ignoring path '%v' from sslpassthrough ingress %v/%vdefaultvault
I1130 22:46:04.678779       5 leaderelection.go:174] attempting to acquire leader lease...
E1130 22:46:04.679447       5 runtime.go:66] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72
/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/home/travis/.gimme/versions/go1.9.2.linux.amd64/src/runtime/asm_amd64.s:509
/home/travis/.gimme/versions/go1.9.2.linux.amd64/src/runtime/panic.go:491
/home/travis/.gimme/versions/go1.9.2.linux.amd64/src/runtime/panic.go:63
/home/travis/.gimme/versions/go1.9.2.linux.amd64/src/runtime/signal_unix.go:367
/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/pkg/common/ingress/controller/controller.go:636
/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/pkg/common/ingress/controller/controller.go:295
/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/pkg/common/ingress/controller/controller.go:177
/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/pkg/common/task/queue.go:112
/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/pkg/common/task/queue.go:59
/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133
/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134
/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/pkg/common/task/queue.go:59
/home/travis/.gimme/versions/go1.9.2.linux.amd64/src/runtime/asm_amd64.s:2337
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xfbc8a8]

goroutine 64 [running]:
github.com/jcmoraisjr/haproxy-ingress/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x111
panic(0x1126b60, 0x1b2bec0)
	/home/travis/.gimme/versions/go1.9.2.linux.amd64/src/runtime/panic.go:491 +0x283
github.com/jcmoraisjr/haproxy-ingress/pkg/common/ingress/controller.(*GenericController).getBackendServers(0xc420358aa0, 0xc4202b8000, 0x1, 0x1, 0x1, 0xc4202b8000, 0x0, 0x1, 0x7ff7b6954b50, 0x6)
	/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/pkg/common/ingress/controller/controller.go:636 +0x2e8
github.com/jcmoraisjr/haproxy-ingress/pkg/common/ingress/controller.(*GenericController).syncIngress(0xc420358aa0, 0x116bca0, 0xc4202c8080, 0xc428410402, 0x13ff02058)
	/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/pkg/common/ingress/controller/controller.go:295 +0x38d
github.com/jcmoraisjr/haproxy-ingress/pkg/common/ingress/controller.(*GenericController).(github.com/jcmoraisjr/haproxy-ingress/pkg/common/ingress/controller.syncIngress)-fm(0x116bca0, 0xc4202c8080, 0xa, 0xc420500d68)
	/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/pkg/common/ingress/controller/controller.go:177 +0x3e
github.com/jcmoraisjr/haproxy-ingress/pkg/common/task.(*Queue).worker(0xc420236b40)
	/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/pkg/common/task/queue.go:112 +0x35b
github.com/jcmoraisjr/haproxy-ingress/pkg/common/task.(*Queue).(github.com/jcmoraisjr/haproxy-ingress/pkg/common/task.worker)-fm()
	/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/pkg/common/task/queue.go:59 +0x2a
github.com/jcmoraisjr/haproxy-ingress/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc420029fa8)
	/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x5e
github.com/jcmoraisjr/haproxy-ingress/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc4204a9fa8, 0x3b9aca00, 0x0, 0x1, 0xc42022e8a0)
	/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xbd
github.com/jcmoraisjr/haproxy-ingress/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc420029fa8, 0x3b9aca00, 0xc42022e8a0)
	/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
github.com/jcmoraisjr/haproxy-ingress/pkg/common/task.(*Queue).Run(0xc420236b40, 0x3b9aca00, 0xc42022e8a0)
	/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/pkg/common/task/queue.go:59 +0x55
created by github.com/jcmoraisjr/haproxy-ingress/pkg/common/ingress/controller.(*GenericController).Start
	/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/pkg/common/ingress/controller/controller.go:1504 +0x3df
```

**Comment by jvanbruegge** [comment]
Downgrading to `v0.6` helps, everything works as expected there

**Comment by jcmoraisjr** [comment]
Hi, thanks for reporting! There are two issues behind this panic. New PR in a few minutes.

Please check if the problem disappear and the controller behaves as expected if you configure `path: /` under `paths` of the ingress that uses ssl-passthrough.

**Comment by jvanbruegge** [comment]
Yes, that works. And with `v0.7-beta.2` the `ssl-redirect` works for `ssl-passthrough`, that was not working before, it just showed the default backend

**Comment by jcmoraisjr** [comment]
`beta.3` was just released, now a missing `paths/path: /` should work as well.

**Comment by jvanbruegge** [comment]
Thanks.
Also thanks for this project, it is one of the best documented I've ever seen
