### ISSUE TITLE
Crash waiting for the external haproxy instance

### ISSUE THREAD

**Issue by jcmoraisjr** [jcmoraisjr/haproxy-ingress#737]
**Description of the problem**

Controller crashes while waiting for the external haproxy instance. Only happens when using haproxy as a sidecar, changing to the embedded approach stop the crashes.

**Expected behavior**

A crash must not happen.

**Steps to reproduce the problem**

Apparently happens only when haproxy is very busy and/or the host has noisy neighborhood - in our deployment calico node started to burn about half of the host's CPUs on all instances that crashed. This is the stack trace:

```
...
I0220 21:14:23.216368       6 instance.go:480] waiting for the external haproxy...
panic: runtime error: slice bounds out of range [:48] with length 38

goroutine 209 [running]:
github.com/jcmoraisjr/haproxy-ingress/pkg/haproxy/utils.buildProcTable.func2(0xc0339a53d8, 0x26, 0x20, 0x30, 0xc0339a53e8, 0x6)
	/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/pkg/haproxy/utils/utils.go:132 +0x123
github.com/jcmoraisjr/haproxy-ingress/pkg/haproxy/utils.buildProcTable(0xc0339a5000, 0x3fe, 0x0)
	/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/pkg/haproxy/utils/utils.go:145 +0x1e3
github.com/jcmoraisjr/haproxy-ingress/pkg/haproxy/utils.HAProxyProcs(0x7ffda2e92a4e, 0x1c, 0x0, 0xc010c69cd8, 0x1)
	/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/pkg/haproxy/utils/utils.go:99 +0x192
github.com/jcmoraisjr/haproxy-ingress/pkg/haproxy.(*instance).reloadExternal(0xc00048db00, 0xc000371900, 0x1)
	/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/pkg/haproxy/instance.go:500 +0x184
github.com/jcmoraisjr/haproxy-ingress/pkg/haproxy.(*instance).reload(0xc00048db00, 0x1882650, 0xc)
	/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/pkg/haproxy/instance.go:455 +0x62
github.com/jcmoraisjr/haproxy-ingress/pkg/haproxy.(*instance).haproxyUpdate(0xc00048db00, 0xc000120280)
	/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/pkg/haproxy/instance.go:302 +0x8c6
github.com/jcmoraisjr/haproxy-ingress/pkg/haproxy.(*instance).Update(0xc00048db00, 0xc000120280)
	/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/pkg/haproxy/instance.go:207 +0x43
github.com/jcmoraisjr/haproxy-ingress/pkg/controller.(*HAProxyController).syncIngress(0xc000172bb0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/pkg/controller/controller.go:353 +0x242
github.com/jcmoraisjr/haproxy-ingress/pkg/utils.(*queue).Run(0xc00048d1a0)
	/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/pkg/utils/queue.go:143 +0x1c7
created by github.com/jcmoraisjr/haproxy-ingress/pkg/controller.(*HAProxyController).startServices
	/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/pkg/controller/controller.go:157 +0x69
```

**Environment information**

HAProxy Ingress version: `v0.12`

Command-line options:

```
        - --v=2
        - --acme-server
        - --acme-track-tls-annotation
        - --master-socket=/var/run/haproxy/master.sock
        - --backend-shards=96
        - --disable-pod-list
        - --buckets-response-time=0.005,0.01,0.02
        - --configmap=ingress-controller/haproxy-ingress
        - --default-ssl-certificate=ingress-controller/ingress-default-tls
        - --default-backend-service=ingress-controller/ingress-default-backend
        - --rate-limit-update=0.5
        - --update-status=false
        - --watch-ingress-without-class
```

**Comment by jcmoraisjr** [comment]
Fixed in v0.12.1. Closing.
